binpash/pash

pa.sh
In some cases (NixOS), /bin/bash doesn't exist. `#!/usr/bin/env bash` is generally more compatible.
=> fix(pa.sh) more cross-distro compatible shebang

compiler/test_evaluation_scripts.sh
Simplify the testing script to not depend on `execute_compile_evaluation_script` and `generate_microbenchmark_intermediary_scripts.py`.
=> Simplify testing

evaluation/eurosys/generate_unix50_scripts.py
`generate_unix50_scripts.py` fails with the following stack trace for `evaluation/unix50/8.txt`, when the system prefers the `ascii` codec.
```
Traceback (most recent call last):
File "generate_unix50_scripts.py", line 44, in <module>
input_file_data = file.read()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28011: ordinal not in range(128)
```
`cat unix50/8.txt | dd ibs=1 skip=28010 count=3` shows that the `ascii` codec tried to decode a Unicode cross character, which appears in a sentence about chessboard dimensions.
The root cause is that `open` will use a platform-specific default encoding, and `ascii` may be used in the context of a container. …
=> Prefer UTF-8 encoding with read and generated UNIX50 files

evaluation/eurosys/execute_unix_benchmarks.sh, scripts/Dockerfile, scripts/remote/README.md, scripts/remote/controller/command.js, scripts/remote/controller/commands/correctness-tests.js, scripts/remote/controller/commands/performance-tests.js, scripts/remote/controller/configs/performance-tests.json, scripts/remote/controller/lib.js, scripts/remote/workers/run-ci.sh, scripts/remote/workers/run-perf.sh
This revision adds Unix50 and EuroSys one liner performance tests, using `-m`.
As of this writing, `memstar.ndr.md` is now configured to use the `workers/run-perf.sh` script, and `ci.pash.ndr.md` are now listening on port 2048 to manage `memstar.ndr.md`. Go ahead and run `curl ci.pash.ndr.md:2048/stdout` to see where the tests are right now. :)
If you wish to run this yourself, check the README in `scripts/remote`.
Notes:
* @angelhof: The Dockerfile has been updated to declare a locale, fixing #106. I ended up needing to do this to get past more and more Python errors when running scripts. Since we discussed it before, can you help me verify that this will not negatively impact artifacts?
* I updated all worker scripts to use empty directories for locks, since `mkdir` is atomic.
* The …
=> Performance test prototype

compiler/pash.py, scripts/install.sh
Here are a couple of paths that needed to be fixed to run the basic pash examples.
Grepping around I noticed lots of others.
Maybe it'd be good to migrate them over to `!#/usr/bin/env bash` too.
=> fix more hardcoded paths to /bin/bash -> /usr/bin/env bash

scripts/install.sh
This PR installs bsd utils for the `col` command. It is not yet ready to merge since we have to make sure that bsd utils do not replace coreutils.
Tests do pass though.
@nvasilakis how can we check that this is indeed the case?
=> Install bsd utils for col

scripts/with-ec2.sh
This script uses the AWS CLI (v2) to 
1. Start an EC2 instance by ID
2. Run a command with the public IP as an argument
3. Stops the instance on exit.
The given command runs on the host so that you can
script interactions between the host and instance. Using
instance IDs allows you to avoid needing to remember an
IP or public domain name (which can also change!).
To run a command on the EC2 host, you can make a script that
accepts the IP argument. Given the following script...
```
#! /bin/bash
ssh -i ~/.ssh/aws.pem "ec2-user@$1" ps aux
```
...this command will show processes on the remote host.
```
with-ec2.sh i-0c8dabedc19aed710 ./ps.sh
```
(This assumes the OpenSSH server is listening at the time the public IP is available!
If this is not acceptable, then make `ps.sh` retry.)
=> Add with-ec2.sh

scripts/aws/ec2/make-ec2.sh, scripts/aws/ec2/suggest-ec2.sh
Added script for creating EC2 instances. `make-ec2.sh` takes no arguments since it uses envvars.
Due to the complexity in the AWS CLI, I included another script called `suggest-ec2.sh`.
It queries your AWS account for data and prints shell code that you can `source` to configure
`make-ec2.sh`.
This gives you a moment to review/adjust variables before creating an instance.
```
./suggest-ec2.sh > env.sh
$EDITOR env.sh
. env.sh
./make-ec2.sh
```
This also allows you to create profiles. Just `source` the one you want.
```
cp env.sh itty-bitty-server.sh
cp env.sh typical-server.sh
cp env.sh big-expensive-monster.sh
$EDITOR ...
```
=> Add make-ec2.sh and suggest-ec2.sh

compiler/pash.py
The current implementation uses a fixed name (pash_immediate_command.sh) to write the input for the command to execute. This might be a problem when executing multiple 'pash -c' commands on the same path as all of them will write on the same file?
=> Fix on pash-c implementation

evaluation/correctness/README.md
I got the link by checking the `origin` url in the Smoosh repo on the prebuilt PaSh image.
=> Add Smoosh repo link to README

compiler/pash_runtime.sh, compiler/pash_runtime_quick_abort.sh, compiler/test_evaluation_scripts.sh, evaluation/tests/grep.sh
Mostly working, however if the sequential is done first, the compiler's log is produced in a delayed fashion, having a little clunky behavior when running in an interactive shell with `-d 1` and without a log_file.
It is not thoroughly tested yet, but we should merge as a first step.
=> Quick abort

compiler/pash_runtime.sh, compiler/pash_runtime_quick_abort.sh, compiler/test_evaluation_scripts.sh
Note: Do not squash, commits have already been squashed to avoid +/- and are conceptually separate.
Improve the robustness of the quick-abort mechanism and identify some more issues.
All one-liner tests now pass using the quick-abort mechanism.
=> Improve robustness of quick-abort

annotations/custom_tr.json, compiler/definitions/ir/nodes/r_wrap.py, compiler/test_evaluation_scripts.sh, evaluation/tests/fun-def.sh
This is a fix to allow r_wrap to execute bash functions. Functions still need to be exported for r_wrap to be able to use them. A better long-term solution would be to only add bash -c when calling r_wrap with a function.
=> Added bash -c for every r_wrap

evaluation/benchmarks/poets/2_1.sh, evaluation/benchmarks/poets/2_2.sh, evaluation/benchmarks/poets/3_1.sh, evaluation/benchmarks/poets/3_2.sh, evaluation/benchmarks/poets/3_3.sh, evaluation/benchmarks/poets/4_3.sh, evaluation/benchmarks/poets/4_3b.sh, evaluation/benchmarks/poets/6_1.sh, evaluation/benchmarks/poets/6_1_1.sh, evaluation/benchmarks/poets/6_1_2.sh, evaluation/benchmarks/poets/6_2.sh, evaluation/benchmarks/poets/6_3.sh, evaluation/benchmarks/poets/6_4.sh, evaluation/benchmarks/poets/6_5.sh, evaluation/benchmarks/poets/6_7.sh, evaluation/benchmarks/poets/7_1.sh, evaluation/benchmarks/poets/7_2.sh, evaluation/benchmarks/poets/8.2_1.sh, evaluation/benchmarks/poets/8.2_2.sh, evaluation/benchmarks/poets/8.3_2.sh, evaluation/benchmarks/poets/8.3_3.sh, evaluation/benchmarks/poets/8_1.sh
Currently PaSh does not handle `set -e` that well and so 6_7.sh in poets when run in bash sequentially exits after the first grep if it finds nothing, while PaSh keeps executing. Commenting out set -e for now for the tests to run and we can comment it back in when we fix the set -e behavior.
=> Comment out set -e in poets

annotations/iconv.json, compiler/test_evaluation_scripts.sh, evaluation/benchmarks/run.par.sh, evaluation/benchmarks/run_all_benchmarks.sh, runtime/auto-split.sh, runtime/dgsh_tee.sh, runtime/eager.sh
Some fixes to ensure that tests and evaluation run without experimental components by default.
Note: Do not squash! I have already squashed and different commits correspond to different changes.
=> Make sure that tests run without experimental flags

compiler/parser/ceda/ast2shell.py
Python printing causes an issue when running `https://github.com/andromeda/pash/blob/fix-printing-braces/evaluation/intro/demo-spell.sh` because it does not properly add the braces after the `&&` in line 7. Therefore, `exit` in Line 9 is always executed!
@mgree and @thurstond is there any issue with adding braces around everything in the printer? Could we add as many braces to be safe?
=> Braces in printing

README.md, evaluation/intro/input/.gitignore, evaluation/intro/test.sh, evaluation/tests/interface_tests/run.sh, run_tests.sh, scripts/run_tests.sh
This PR adds a top-level testing script and polishes the `interface_tests` testing script.
This testing script can then be used before pushing/merging PRs through a CI.
=> Add a top-level tests script

compiler/ast_to_ir.py, compiler/parser/ceda/ast2a.py, compiler/parser/ceda/ast2shell.py, evaluation/tests/interface_tests/loop1.sh, evaluation/tests/interface_tests/run.sh
The `loop1.sh` testcase (simplified from a POSIX test) is parsed wrongly by pash which only parses the first loop argument `A` and not `B`.
One can reproduce this by running `$PASH_TOP/pa.sh -d 1 loop1.sh` with the added logs in this branch to see that it is a parsing issue.
@thurstond, @mgree do you have any ideas what could be the problem?
=> Loop argument parsing issue

evaluation/benchmarks/oneliners/wf.sh
Word frequencies seems to have a bug in its invocation of `tr -cs` (a missing space).
=> Fix space in wf's `tr`

compiler/pash_runtime.sh, evaluation/tests/interface_tests/run.sh, evaluation/tests/interface_tests/tilde.sh
Redirect the output of `pash_runtime` to a log to ensure that it doesn't get mixed up (this is particularly important when changes in the environment lead to `import` failures).
Interface `test9` exhibits that behavior.
=> Redirect the output of pash_runtime to the log

compiler/definitions/ast_node.py, compiler/pash_set_from_to.sh, compiler/pash_wrap_vars.sh, evaluation/tests/interface_tests/run.sh, evaluation/tests/interface_tests/set-e-2.sh, evaluation/tests/interface_tests/set-e-3.sh
PaSh currently sources parts of the script in the context of `&&` and `||` and based on the bash documentation, this prevents `set -e` from working (focus in bold):
> -e
>
>    Exit immediately if a pipeline (see Pipelines), which may consist of a single simple command (see Simple Commands), a list (see Lists), or a compound command (see Compound Commands) returns a non-zero status. The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test in an if statement, **part of any command executed in a && or || list** except the command following the final && or ||, any command in a pipeline but the last, or if the command’s return status is being inverted with !. If a compound command other than a subshell …
=> Set-e does not apply when executing in the context of `&&` or `||`

compiler/pash_init_setup.sh, compiler/pash_ptempfile_name.sh, compiler/test_evaluation_scripts.sh, runtime/auto-split.sh, runtime/wait_for_output_and_sigpipe_rest.sh, scripts/setup-pash.sh
Added a local config file `~/.pash_init` that currently holds the distro information (and potentially other data we could add in the future). This file is sourced once during the bootstrap of `compiler/pash_init_setup.sh`
=> Reduce the number of calls related to distro discovery

runtime/agg/cpp/aggregators/wc/agg-linux.h, runtime/agg/cpp/aggregators/wc/common.h
Since g++11, it is required to include `<limits.h>` in the code.
=> Include limits.h to comply with g++11 version [skip ci]

compiler/config.py, compiler/pash.py, compiler/pash_runtime.sh, compiler/pash_runtime_daemon.py, compiler/util.py, evaluation/tests/interface_tests/cmd_sbst.sh, evaluation/tests/interface_tests/run.sh, pa.sh
I resolved this. I also added `--pash_parallel_pipelines` always in interface tests even though it is experimental to make sure that it always passes all the tests.
=> Parallel Pipelines extension does not revert bash state correctly

evaluation/benchmarks/runtime-overhead/for-echo.sh, evaluation/benchmarks/runtime-overhead/run.sh
On my machine (very not-representative, Windows WSL) running `run.sh` returns:
```
bash:                                    0.005
PaSh_no_daemon:                          11.284
PaSh_daemon_bash_mirror:                 30.938
PaSh_daemon:                             5.447
PaSh_daemon_fifos:                       5.095
PaSh_daemon_par_pipelines:               2.702
PaSh_daemon_par_pipelines_fifos:         2.701
```
=> Add a mini-experiment that checks the runtime overhead in a tight loop

compiler/pash_runtime_daemon.py
Fix a bug where pash gets stuck when invoked using `--help`.
```sh
pa.sh --help
```
=> Remove help from daemon so that it doesn't get stuck

compiler/ast_to_ir.py, compiler/ast_util.py, compiler/ir_to_ast.py, compiler/ir_utils.py, compiler/pash_runtime.sh, evaluation/benchmarks/runtime-overhead/for-echo.sh, evaluation/tests/interface_tests/cat-redir-fail.sh, evaluation/tests/interface_tests/run.sh, runtime/wait_for_output_and_sigpipe_rest.sh
This PR tries to add support for returning the exit status of pash-compiled pipelines. These changes fix the issue in general but there is still a failure with `--parallel_pipelines` since this flag executes pipelines in the background and therefore their exit status is lost.
@mgree, @tammam1998 the problem is here: https://github.com/binpash/pash/blob/cat-redir-fail/compiler/pash_runtime.sh#L233. Is there any way to address this without losing support for parallel pipelines?
=> Exposing the exit status of pash-compiled pipelines

compiler/pash_init_setup.sh, compiler/pash_runtime_daemon.py, evaluation/benchmarks/run.par.sh, evaluation/tests/spell-grep.sh
This PR contains fixes or changes so that pash works on livestar.
1. It modifies `nc -z` to not use that flag to check if daemon is listening since for some reason, the `nc` version on livestar always returns 1 even if it is connected.
2. Modifies test input for `spell-grep` for tests to take reasonable time.
=> Livestar fixes

evaluation/benchmarks/run.par.sh, evaluation/benchmarks/run_all_benchmarks.sh
Let's not run `-d 1` by default when running benchmarks, since debugging adds significant overhead. @dkarnikis we should make sure to run experiments from now without `-d 1`. If you need to get a log to debug, you can call `run_all_benchmarks.sh` with `--debug`.
=> Disable debugging when running benchmarks by default

compiler/config.py
Changed the default param just in case we ever forget to add --r_split_batch_size 1000000
=> change default r_split batch size param

annotations/diff.json
@nvasilakis  Can you think of a reason why we had `diff` be non-pure? I don't see why `diff` is not pure by default.
@dkarnikis after/if we merge this we should rerun `oneliners/diff.sh`
=> Fix an issue with diff annotation

README.md
- fix broken link for evaluation scripts
- make markdown formatting consistent
=> (docs) fix broken link and fmt README.md

scripts/distro-deps.sh
PaSh needs the openbsd version of `netcat` since it uses it for unix-socket communication. This addresses part of the issue in: #434
=> Install netcat-openbsd 

runtime/r_merge.c, runtime/r_split.h, runtime/r_unwrap.c, runtime/r_wrap.c
This is a rare bug that happens sometimes when some processes terminate before the sigterm signal reaches other processes. This bug happens non deterministically (only sometimes) on 20.sh and 34.sh with width 16.
=> fix bug caused by early kill of process

README.md
The link was broken and since there is only one single file in the directory, I changed it to point it to this one.
=> Fix link to guide for contributing

README.md
Now that PaSh is [officially supported by the Linux foundation](https://linuxfoundation.org/press-release/linux-foundation-to-host-the-pash-project-accelerating-shell-scripting-with-automated-parallelization-for-industrial-use-cases/), I think this information could be added to the `README`. I used the phrase "hosted by" as it is a citation from the press release:
> The Linux Foundation, [...], today announced it will host the PaSh project.
=> Add information about the Linux Foundation

evaluation/benchmarks/oneliners/shortest-scripts.sh
The original file was not a list of commands and does not really make sense for the script I think. From the input folder, the file `all_cmds.txt` was reasonable to choose but I do not exactly know whether this was the original intention.
=> Fix input file for shortest scripts, i.e., make it all_cmds

compiler/ir_to_ast.py
If the user doesn't set termination to clean_up_graph, the compiler tries to add a `wait` command to wait for all processes. However, there was a bug in how we added the wait command which causes the compilation to fail. We also didn't report `internal_exec_status` after `wait` which is required at the end of the generated script.
=> Fix bug causing graph compilation to fail if termination clean_up_graph flag wasn't set

pa.sh
- Kill pending processes running under the current instance of pash (killed by signal)
- Doesn't affect the performance of other running pash instances
(Moved from https://github.com/binpash/pash/pull/454)
=> Kill processes that are exclusively under the current process tree

compiler/test_evaluation_scripts.sh, evaluation/benchmarks/dependency_untangling/input/install-deps.sh, evaluation/benchmarks/dependency_untangling/input/setup.sh, evaluation/eval_script/run_all.sh
1. Install missing package for log processing benchmark (tcpdump)
2. Replace dead links for media conversion benchmark
=> Broken eval

.github/workflows/docker.yaml
* Build Ubuntu-18.04, debian:10 and fedora:35 on each new package release.
* The images are built and pushed automatically on dockerhub (can be expanded to other registries as well)
=> Auto-build docker images on new releases and push to dockerhub

annotations/hdfs.json, compiler/definitions/ir/file_id.py, compiler/definitions/ir/nodes/hdfs_cat.py, compiler/definitions/ir/resource.py, compiler/dspash/hdfs_file_data.py, compiler/dspash/hdfs_utils.py, compiler/dspash/ir_helper.py, compiler/dspash/worker.sh, compiler/dspash/worker_manager.py, compiler/ir.py, compiler/pash_runtime.py
Extends the distributed execution mode to handle HDFS cat commands. The PR contributes changes on two levels: 
Compiler: 
- To handle HDFS I introduced a new a`RemoteFileResource` interface and `HDFSResource` implements this interface. The hdfs file resource contains information about a block and all the machines the block exists on.
- HDFSCat DFGNode is added. This node is then removed in the graph optimizing step and replaced by Cat nodes where each cat fid has an HDFSResource that corresponds to a block of the HDFS file.
Distributed Execution:  The worker manager policy now takes into account data availability when choosing a worker.
=> HDFS cat support

compiler/definitions/ir/file_id.py, compiler/definitions/ir/resource.py, compiler/ir.py, compiler/pash_runtime.py
A previous intermediate filename of the eager runtime is such as `/path/to/tmpdir/prefix_#fifo1`, even though it's a normal file but not a FIFO. This name doesn't make sense, even if it probably has no direct effect on users. So change the filename to indicate that it is a normal file. The fixed filename is such as `/path/to/tmpdir/prefix_1`.
=> Fix the eager runtime intermediate filenames

compiler/ast_to_ir.py, compiler/dspash/ir_helper.py, compiler/pash.py, compiler/pash_runtime.py, compiler/pash_runtime_daemon.py, compiler/util.py
PaSh did not close tempfile file descriptors and this PR fixes it.
=> Fix a fd leak issue

compiler/ast_to_ir.py, pa.sh
@nvasilakis is there any way this resolves the installation issues?
=> Append to pythonpath instead of setting it

compiler/dspash/worker.sh, compiler/pash_runtime_quick_abort.sh, evaluation/osdi22-eval/run_all.sh, evaluation/other/circular/sq.sh, pa.sh
A variety of scripts use the `function` keyword to define functions, which isn't POSIX. This PR drops that keyword from all scripts except for `other/circular/sq.sh` (I wanted to preserve that for evaluation).
It's not an issue per se---these scripts are already in `bash`, so there's no serious harm in having it there... except I was using those scripts to test the libdash bindings, and it broke them.
=> Drop function kw

.github/workflows/tests.yaml
Currently we're using the default `fail-fast: true`, but this means a failure due to 18.04's Python 3.6 in #616 means we can't see how 20.04 does.
Debugging CI sucks lol.
=> Run tests in Ubuntu 18.04 and 20.04 to completion

.github/workflows/tests.yaml
Github Actions are deprecating Ubuntu 18.04 (https://github.com/actions/runner-images/issues/6002), which was already causing us issues due to an old Python version (3.6). Therefore, we can just remove it from the CI and run on Ubuntu 20 and 22 instead
=> Don't run PaSh Github CI on Ubuntu 18.04 due to deprecation

.github/workflows/posix.yaml, scripts/ws-client.py
=> Add a python script to contact the POSIX test server

compiler/config.py, compiler/expand.py, compiler/pash.py, compiler/pash_runtime_daemon.py, scripts/setup-pash.sh
The `pexpect` import is no longer needed since it was only used to evaluate a slower configuration of PaSh. I removed pexpect from the installation and from everywhere in PaSh.
=> Remove pexpect and add a deprecation warning

compiler/ir.py, scripts/distro-deps.sh, scripts/setup-pash.sh
Clean up the setup scripts by removing unnecessary components and by preserving all output for better debugability.
=> Cleanup setup scripts

scripts/docker/debian/Dockerfile
The debian docker image is used to run the POSIX tests so we need to update it to python3.8 to be able to run them properly.
=> Update debian docker image to have python3.8

.github/workflows/build.yaml, .github/workflows/posix.yaml, .github/workflows/tests.yaml, .github/workflows/tight-loop.yaml
There is no benefit in not triggering CI on scripts changes. We are often required to do whitespace changes to trigger it.
=> Trigger CI on scripts changes

compiler/pash.py, compiler/preprocessor/preprocessor.py, compiler/shell_ast/ast_to_ast.py, compiler/util_spec.py
Use by running the following when on `$PASH_TOP`.
```sh
./compiler/preprocessor/preprocessor spec input.sh partial_order.sh
```
It will save a sequence of commands in `partial_order.sh.`
For now it is very janky since it prints each command in its own line (but this can fail very badly if commands contain newlines).
TODO: We need to fix this to print each command in its own file, and the partial order file should only contain the ids of the commands and their ordering. I need to add a new directory `speculation` in compiler, that will contain relevant code.
=> Allow preprocessor to extract sequence of commands

compiler/preprocessor/preprocessor.py, compiler/shell_ast/ast_to_ast.py, compiler/speculative/util_spec.py, compiler/util_spec.py
Properly serialize the different df regions when spec preprocessing and only add the edges to the po file.
Use by running the following when in `$PASH_TOP`.
```sh
./compiler/preprocessor/preprocessor spec input.sh partial_order.txt
```
The `partial_order.txt` file will look like this:
```sh
/tmp/pash_BYmDfbB//speculative/partial_order/
0 -> 1
...
```
where the path is the directory that stores different df regions. For example, region `0` is stored in `/tmp/pash_BYmDfbB//speculative/partial_order/0` for that particular example. Furthermore, the arrows show the partial order of df_regions in the original file (for now it is always a sequence, but it can be extended to be a partial order.
TODO: The next step is to add a proper entry point in PaSh that will wait for the scheduler at each …
=> Add df regions to their own files and only edges to the po file

compiler/ast_to_ir.py, compiler/parse.py, compiler/preprocessor/preprocessor.py, compiler/shell_ast/ast_node.py, compiler/shell_ast/ast_to_ast.py, compiler/shell_ast/ast_util.py, compiler/shell_ast/untyped_to_ast.py
The goal of this PR is to implement the first step towards resolving #671.
=> Clean up shell AST

requirements.txt
PaSh Annotations will have some breaking changes introduced soon to its new minor version, so I pin its version to 0.2
=> Pin pash-annotations version

compiler/cli.py, compiler/config.py, compiler/pash.py, compiler/pash_compilation_server.py, compiler/pash_compiler.py, compiler/preprocessor/preprocessor.py
I personally had great difficulty navigating multiple different files to figure out how to add flags, modify flags, etc. This PR gathers all the CLI argparsers into a single `compiler/cli.py` file.
This also removes the deprecated flags from the argparsers and changes scripts accordingly.
=> Move all ArgParser variants to single cli.py module

compiler/definitions/ir/dfg_node.py, compiler/definitions/ir/nodes/dfs_split_reader.py, compiler/definitions/ir/nodes/dgsh_tee.py, compiler/definitions/ir/nodes/eager.py, compiler/definitions/ir/nodes/hdfs_cat.py, compiler/definitions/ir/nodes/pash_split.py, compiler/definitions/ir/nodes/r_merge.py, compiler/definitions/ir/nodes/r_split.py, compiler/definitions/ir/nodes/r_unwrap.py, compiler/definitions/ir/nodes/r_wrap.py, compiler/definitions/ir/nodes/remote_pipe.py, compiler/dspash/worker_manager.py, compiler/ir.py, compiler/shell_ast/ast_util.py
Fixes #485 
Replace lists as default arguments with the `var = [] if var is None else var` pattern.
=> Remove lists as default arguments in functions

compiler/config.py, compiler/pash_compilation_server.py, compiler/pash_compiler.py, pa.sh, requirements.txt
Use the bash version to determine how to parse the vars file as discussed in binpash/sh-expand#7. Should be merged at the same time as those changes (and will fail any tests until then).
=> Add passing bash version to read_vars_file

compiler/orchestrator_runtime/pash_prepare_call_compiler.sh, compiler/orchestrator_runtime/speculative/speculative_runtime.sh, evaluation/tests/interface_tests/run.sh, evaluation/tests/interface_tests/test-IFS.sh, runtime/wait_for_output_and_sigpipe_rest.sh
Resolves #718. In a few places, the default value of IFS is assumed, leading to pa.sh crashing when it’s reset. This saves the old IFS and restores it after the word splitting.
=> Set IFS to default before use in compiler.

compiler/pash_compilation_server.py, compiler/pash_runtime.sh
Fixes #736, #738. This wasn’t a problem on Ubuntu 20.04 because the EXIT handler wasn’t called (for no obvious reason), so it only exited once.
=> Fix double exit bug in parallel pipelines

.github/workflows/canary.yml, .github/workflows/docker.yaml, .github/workflows/ghcr.yaml, docs/contributing/contrib.md, scripts/docker/README.md, scripts/docker/debian/Dockerfile, scripts/docker/fedora/Dockerfile, scripts/docker/ubuntu/Dockerfile
Separate from #745 in case we want to wait and see if it causes any problems.
Separately, the docker containers are a bit out of date (last pushed May 2023), so could whoever has permissions to update those push the new version? (although I’m not sure how important those are to keep up to date).
=> Upgrade CI to latest OS versions
