binpash/pash

scripts/Dockerfile

Add Dockerfile to simplify creating a local docker image.

Add Dockerfile

---

compiler/superoptimize.sh
pa.sh

This creates a quick-and-easy way to plug in the superoptimization work. The flag will eventually find its way into the Python side, but for now this calls a `compiler/superoptimize.sh` script that could serve as a starting point.

Add a superoptimizer hook

---

scripts/ssh-install.sh

Clone the repo straight from github when running the tests in ec2

---

scripts/ssh-install.sh

Correct an issue where ssh-install does not checkout the correct branch

Properly switch to the correct branch in ssh-install

---

compiler/parser/Makefile
compiler/parser/README.md
pa.sh
scripts/install.sh

Remove PASH_PARSER variable from  the code.

Remove PASH_PARSER

---

runtime/agg/opt/add.sh
runtime/agg/opt/concat.sh
runtime/agg/opt/count.sh
runtime/agg/opt/head.sh
runtime/agg/opt/tail.sh
runtime/agg/opt/uniq-c.2.sh
runtime/agg/opt/uniq.sh
runtime/agg/opt/wc.2.sh
runtime/agg/opt/wc.sh
runtime/auto-split.sh
runtime/bigrams_aux_map.sh
runtime/cat_output_files.sh
runtime/distributed.sh
runtime/drain_stream.sh
runtime/eager-no-task-par.sh
runtime/eager.sh
runtime/eager_test.sh
runtime/merge-uniq.sh
runtime/merge-wc.sh
runtime/multiply.sh
runtime/page-per-line.sh
runtime/pretty_print_json.sh
runtime/redirect_stdin_to.sh
runtime/wait_for_output_and_sigpipe_rest.sh

every script in runtime has now a portable path

fix path in runtime scripts

---

scripts/remote/controller/configs/correctness-tests.json

Update correctness test worker host

---

compiler/ast_to_ir.py
compiler/config.py
compiler/ir_to_ast.py
compiler/pash.py
compiler/pash_ptempfile_name.sh
compiler/pash_runtime.py
compiler/pash_runtime.sh
compiler/pash_runtime_quick_abort.sh
compiler/util.py

Subsumes #115 
PaSh now nests all files under the same directory.
It also creates a different directory per execution.
Finally, it deletes this temporary directory if not under debugging mode.

Nest all pash temp files under the same directory.

---

compiler/gather_results.py
evaluation/scripts/input/gen_big_files.sh

Generate 3G file in `gen_big_files.sh` and modify plotting script to restrict which plots it generates.

Minor modifications to facilitate AE

---

scripts/pash-nginx.conf
scripts/remote/controller/command.js
scripts/remote/controller/lib.js
scripts/remote/controller/perf-analysis/plot.html

As per subject. This adds patches to make performance tests behave on beta.

Adjustments for performance tests on beta

---

docs/eval.md

This adds a markdown file with a tutorial for the EuroSys artifact evaluation committee.

Add AEC tutorial

---

annotations/c_stats/posix.txt
annotations/nl.json
annotations/p_stats/coreutils-summary.txt
annotations/p_stats/get-summary.sh
annotations/p_stats/posix-summary.txt
annotations/sort.json
annotations/tests/cmd-nl.sh
annotations/tests/cmd-wc.sh
annotations/tests/test-core.sh
annotations/tests/test.sh
annotations/wc.json

This builds a basic infrastructure for testing annotations and aggregators.

Infra for checking that aggregators work as expected

---

scripts/ci-perf.sh

Make `ci-perf.sh` use only Bash. I also set `ci-perf.sh` so that you can either execute it, or source it. That proves helpful when one part of the script doesn't work and you need to iterate on that part.
Note that I verified this without running performance tests. I did this by iterating only on the `summarize_perf_suite` function. I don't expect this to be a problem because that's the only part of the code being replaced from the test runner's perspective.
Unblocks #139

Use only Bash when summarizing performance test results

---

evaluation/eurosys/execute_max_temp_dish_evaluation.sh
evaluation/eurosys/execute_web_index_dish_evaluation.sh
evaluation/execute_compile_evaluation_script.sh

Minor improvement that allows for multiple user execution of evaluation

Modify some pash outputs to go to local files instead of /tmp

---

compiler/pash_runtime.py

Catch all unhandled exceptions at the top of the runtime

---

evaluation/intro/demo-spell.sh
evaluation/intro/input/setup.sh

Quickfix demo-spell

---

README.md
docs/tutorial.md
scripts/distro-deps.sh

- Update on distro-debs
- Update on Readme

Debian deps

---

README.md
docs/tutorial.md
docs/windows.md

Step-by-step guide to setup WSL and install PaSh

PaSh installation for Windows WSL

---

docs/windows.md

Add some missing steps in the WSL2 installation process and describe it more throughoutly.

Make WSL2 installation instructions more detailed

---

scripts/dockerfiles/README.md
scripts/dockerfiles/debian/Dockerfile
scripts/dockerfiles/fedora/Dockerfile
scripts/dockerfiles/ubuntu/Dockerfile

TODO: Include them to the docs

Dockerfiles for ubuntu, debian, fedora

---

evaluation/benchmarks/poets/8.2_2.sh

First calculate all the bigrams ([4_3.sh](https://github.com/binpash/pash/blob/main/evaluation/benchmarks/poets/4_3.sh) script) and based on the generated output calculate all the bigrams that appear twice

bigrams that appear twice Fix

---

annotations/head.json

Fix the `head` annotation so that tests pass.

Head annotation fix

---

evaluation/benchmarks/poets/1_1.sh
evaluation/benchmarks/poets/6_1.sh
evaluation/benchmarks/poets/6_1_1.sh
evaluation/benchmarks/poets/6_1_2.sh
evaluation/benchmarks/poets/6_2.sh
evaluation/benchmarks/poets/6_4.sh
evaluation/benchmarks/poets/6_5.sh
evaluation/benchmarks/poets/6_7.sh
evaluation/benchmarks/poets/7_2.sh
evaluation/benchmarks/poets/8.2_1.sh
evaluation/benchmarks/poets/8.3_2.sh
evaluation/benchmarks/poets/8_1.sh
evaluation/benchmarks/poets/input/setup.sh

On script [6_1.sh](https://github.com/binpash/pash/pull/294/files#diff-e9beb2c7b12f38608013f7679b1ea45e7a09f1cbcb671b1a855d28286a7a6170), I don't get the same output as the original UnixforPoets script.

Poets fixes

---

compiler/config.json
compiler/definitions/ir/file_id.py
compiler/ir.py
compiler/pash.py
compiler/pash_init_setup.sh
compiler/pash_runtime.py
compiler/pash_runtime.sh
compiler/pash_runtime_daemon.py
compiler/pash_wrap_vars.sh
compiler/test_evaluation_scripts.sh
pa.sh
runtime/wait_for_output_and_sigpipe_rest.sh

Execute pipelines in parallel if there is no conflict and compilation succeeds

Parallel pipelines

---

annotations/cat.json
compiler/annotations.py
compiler/definitions/ir/dfg_node.py
compiler/definitions/ir/file_id.py
compiler/test_evaluation_scripts.sh
evaluation/tests/interface_tests/exec-redirections.in
evaluation/tests/interface_tests/exec-redirections.sh
evaluation/tests/interface_tests/run.sh

[WIP] Issue with cat annotation

---

compiler/pash_runtime.sh
evaluation/tests/interface_tests/run.sh
evaluation/tests/interface_tests/trap.sh

This might an overconservative check but we can relax it once we make sure how to do it correctly.

No parallel pipelines if there are traps

---

compiler/pash_init_setup.sh
evaluation/benchmarks/run_all_benchmarks.sh

Fail early when speculation is invoked

---

compiler/config.py

Increasing the recursion limit since unparsing seems to reach it for bigger graphs.

Increase recursion limit

---

compiler/config.py
compiler/pash_init_setup.sh
compiler/pash_runtime.py
compiler/pash_runtime.sh
compiler/pash_runtime_daemon.py
evaluation/benchmarks/profile-driven/README.md
evaluation/benchmarks/profile-driven/for-loop.sh
evaluation/tests/interface_tests/run.sh

This PR introduces profile-driven width lowering. If the same part of a script is recompiled, the daemon determines its width based on past execution times.

Profile driven width lowering

---

compiler/config.py
compiler/ir.py
compiler/ir_to_ast.py
compiler/ir_utils.py
compiler/pash_ptempfile_name.sh
compiler/pash_runtime.sh
compiler/pash_runtime_daemon.py
compiler/util.py
evaluation/benchmarks/poets/8.3_2.sh
runtime/wait_for_output_and_sigpipe_rest.sh

Instead of finding which pids we need to stop afterwards, we now do it while spawning them. This should improve performance.

Gather pids to kill when spawning

---

evaluation/benchmarks/max-temp/temp-analytics.sh
evaluation/benchmarks/poets/8.3_2.sh

@dkarnikis Whenever (no rush, and do not modify the other schedules) you have some time, could you get one run for all configs of anagrams with this PR?

anagrams mini change to avoid unneccessary intermediate file

---

compiler/pash.py

Solve empty command hanging issue

---

compiler/test_evaluation_scripts.sh

@dkarnikis if tests pass, we should merge :)

Test the experimental flags

---

evaluation/benchmarks/poets/1_1.sh
evaluation/benchmarks/poets/2_1.sh
evaluation/benchmarks/poets/2_2.sh
evaluation/benchmarks/poets/3_1.sh
evaluation/benchmarks/poets/3_2.sh
evaluation/benchmarks/poets/3_3.sh
evaluation/benchmarks/poets/4_3.sh
evaluation/benchmarks/poets/4_3b.sh
evaluation/benchmarks/poets/6_1.sh
evaluation/benchmarks/poets/6_1_1.sh
evaluation/benchmarks/poets/6_1_2.sh
evaluation/benchmarks/poets/6_2.sh
evaluation/benchmarks/poets/6_3.sh
evaluation/benchmarks/poets/6_4.sh
evaluation/benchmarks/poets/6_5.sh
evaluation/benchmarks/poets/6_7.sh
evaluation/benchmarks/poets/7_1.sh
evaluation/benchmarks/poets/7_2.sh
evaluation/benchmarks/poets/8.2_1.sh
evaluation/benchmarks/poets/8.2_2.sh
evaluation/benchmarks/poets/8.3_2.sh
evaluation/benchmarks/poets/8.3_3.sh
evaluation/benchmarks/poets/8_1.sh
evaluation/benchmarks/poets/test.sh
evaluation/benchmarks/run.par.sh
evaluation/benchmarks/run.seq.sh

Signed-off-by: dkarnikis <dkarnikis>

Add the correct input size to the run scripts

---

README.md
docs/contributing/contrib.md
docs/tutorial/tutorial.md

Fix various broken links in READMEs and tutorials

Fix broken links

---

.github/workflows/cicd.yaml
compiler/config.py
compiler/pash_init_setup.sh
pa.sh

show pash version

---

evaluation/benchmarks/for-loops/input/install-deps.sh
evaluation/benchmarks/for-loops/input/setup.sh
evaluation/benchmarks/run.seq.sh

Dataset setup WIP

---

scripts/setup-pash.sh

This PR should address https://github.com/binpash/pash/issues/434

Fix for python pkgs in pash setup

---

.github/workflows/main.yml

CI setup fix

---

.github/workflows/main.yml
compiler/pash.py
scripts/distro-deps.sh
scripts/docker/debian/Dockerfile
scripts/docker/fedora/Dockerfile
scripts/docker/ubuntu/Dockerfile
scripts/install.sh
scripts/setup-pash.sh

- Fixed dockerfiles for ubuntu, debian and fedora.
- Moved all the deps inside `distro-deps.sh`
- Removed sudo from original installation scripts
`git` is the only package required in the dockerfiles (in order to fetch the repo).
This PR includes https://github.com/binpash/pash/pull/439 and should fix https://github.com/binpash/pash/issues/438
Signed-off-by: dkarnikis <dkarnikis>

Dockerfiles fix

---

README.md
docs/tutorial/tutorial.md

Signed-off-by: Glenn Visser <gvr340@student.vu.nl>

Adjusted docs

---

.github/workflows/main.yml
scripts/docker/debian/Dockerfile
scripts/docker/fedora/Dockerfile
scripts/docker/ubuntu/Dockerfile
scripts/setup-pash.sh

Addresses https://github.com/binpash/pash/issues/450

export PASH_TOP and PATH after pash installation

---

scripts/distro-deps.sh

Need openbsd-netcat in Arch Linux

---

.github/workflows/main.yml
docs/tutorial/tutorial.md
runtime/Makefile
scripts/distro-deps.sh
scripts/install.sh

Signed-off-by: Dimitris Karnikis [dkarnikis@gmail.com](mailto:dkarnikis@gmail.com)

Make g++ optimized aggregators optional

---

.github/workflows/main.yml

Patch to Github CI to address pash flag changes

---

README.md

I think it makes sense to have the citation (and/or the main paper) accessible somewhere in the README. 
I wrote a stub, which we can improve to add more info or modify the text.

PaSh citation in README

---

docs/troubleshooting.md
evaluation/benchmarks/oneliners/shortest-scripts.sh

When setting up PaSh, I encountered some obstacles I could not solve with the current documentation.
@dkarnikis explained how to overcome them. Following advice by him and @nvasilakis, I summarized this as a first item in a list for troubleshooting.

Add file about troubleshooting in docs

---

README.md
docs/contributing/contrib.md
docs/install/README.md
docs/tutorial/tutorial.md

This creates a single location where all installation instructions reside, so that they do not fall out of sync. It also fixes several mistakes and adds links to the discord server.

Small documentation fixes

---

evaluation/benchmarks/analytics-mts/input/setup.sh
evaluation/benchmarks/oneliners/input/setup.sh
evaluation/benchmarks/run.par.sh
evaluation/benchmarks/run.seq.sh
evaluation/benchmarks/unix50/input/setup.sh
evaluation/benchmarks/web-index/input/setup.sh

Signed-off-by: Dimitris Karnikis [dkarnikis@gmail.com](mailto:dkarnikis@gmail.com)

Setup dataset/runner fixes

---

compiler/test_evaluation_scripts.sh
evaluation/intro/test.sh
evaluation/tests/interface_tests/run.sh
scripts/workflow/get_results.sh
scripts/workflow/parse.sh

Workflow fixes to include agg tests

---

.github/workflows/posix.yaml

Generate the execution results of posix and correctness tests (including the posix output journal)

Upload artifact

---

.github/workflows/posix.yaml

Fix correctness table

---

compiler/definitions/ir/dfg_node.py

This patch is a just trivial typo fix.

Fix typo in a comment

---

README.md

correct repo name

---

.github/workflows/docker.yaml
.github/workflows/ghcr.yaml
.github/workflows/posix.yaml
.github/workflows/tight-loop.yaml

* Update job/task names
* Add ci to push docker images to github registry
* Don't run tests on draft PRs
* Run tight-loops on github servers and store their artifact (instead of custom worker)

Pipelines changes

---

.github/workflows/performance.yaml

Trigger performance tests only

---

annotations/custom_sort.json
compiler/pash_runtime.py

Fix fun-def compilation issue #488.

Fix custom_sort annotation

---

compiler/dspash/remote_exec_graph.sh
compiler/dspash/utils.py
compiler/dspash/worker.py
compiler/dspash/worker_manager.py
compiler/pash_runtime.sh

Adds support for functions in distributed execution mode

Dist functions

---

README.md

Modify readme badge links

---

.github/workflows/ghcr.yaml
compiler/config.py

Also update version to do a new release.

CI Fix to not push multiple images on Github Images

---

.github/workflows/tests.yaml
compiler/pash_runtime.sh

[Shellcheck test]

---

annotations/rev.json

Needed for NLP benchmark sort_words_by_rhyming (3_3.sh)

Added annotation for rev

---

compiler/parser/ceda/parse_to_ast2.py

It looks like already done by using PASH_TOP which points PaSH's project root.

Remove an outdated TODO comment

---

TODO.md
compiler/annotations_utils/util_cmd_invocations.py
compiler/definitions/ir/dfg_node.py
compiler/definitions/ir/nodes/eager.py
compiler/definitions/ir/nodes/r_merge.py
compiler/definitions/ir/nodes/r_unwrap.py
compiler/definitions/ir/nodes/r_wrap.py
compiler/ir.py
compiler/ir_utils.py
compiler/pash_runtime.py

Including unwrap for commutative commands

Support for round-robin parallelization with new annotations

---

compiler/pash_runtime.py

Fix unwrap and commutative interplay

---

TODO.md
compiler/annotations_utils/util_cmd_invocations.py
compiler/definitions/ir/dfg_node.py
compiler/definitions/ir/nodes/dgsh_tee.py
compiler/pash_runtime.py

Add support for dgsh_tee nodes

---

TODO.md
compiler/definitions/ir/dfg_node.py
compiler/ir.py
compiler/pash_runtime.py

Separated parallelization into choose and apply phases

---

TODO.md
compiler/ir.py

Fuse cat and subsequent split

---

README.md
scripts/distro-deps.sh
scripts/setup-pash.sh
scripts/up.sh
scripts/utils.sh

[..currently testing, will update when done...]

More installation fixes

---

compiler/ir.py
compiler/pash_runtime.py

Fuse r_merge and subsequent commutative command

---

TODO.md
compiler/annotations_utils/util_aggregator.py
compiler/annotations_utils/util_cmd_invocations.py
compiler/annotations_utils/util_file_descriptors.py
compiler/annotations_utils/util_mapper.py
compiler/annotations_utils/util_parsing.py
compiler/config.py
compiler/definitions/ir/dfg_node.py
compiler/ir.py
scripts/setup-pash.sh

"Properly" install and import the annotations library (instead of just adding it to the path).

Install annotations lib using `pip`

---

compiler/definitions/ir/nodes/dgsh_tee.py
compiler/definitions/ir/nodes/eager.py
compiler/definitions/ir/nodes/r_merge.py
compiler/definitions/ir/nodes/r_split.py
compiler/definitions/ir/nodes/r_unwrap.py
compiler/definitions/ir/nodes/r_wrap.py

Refactored to remove __future__ from annotations library

---

compiler/definitions/ir/nodes/cat.py
compiler/ir.py

Add support for bigrams

---

compiler/ir.py

Refactor to have defaults for AnnotationInfo

---

.github/workflows/tests.yaml

Temporarily remove Ubuntu 22.04 from the CI until it is debugged

---

compiler/env_var_names.py
compiler/orchestrator_runtime/speculative/speculative_runtime.sh
compiler/preprocessor/preprocessor.py
compiler/shell_ast/ast_to_ast.py
compiler/shell_ast/ast_util.py
compiler/speculative/util_spec.py

Spec loop support
